[package]
name = "tetris_sdl2"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
chargrid_sdl2 = { path = "../../../sdl2", features = ["gamepad"] }
tetris_app = { path = "../app" }
rand = "0.8"
env_logger = "0.10"
