[package]
name = "component_experiment_web"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chargrid_web = { path = "../../../web" }
component_experiment_app = { path = "../app" }
wasm-bindgen = "0.2"
