[package]
name = "chargrid_wgpu"
description = "Graphical chargrid context which renders with wgpu"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gridbugs/chargrid.git"
repository = "https://github.com/gridbugs/chargrid.git"
documentation = "https://docs.rs/chargrid_wgpu"
edition = "2021"

[features]
serialize = ["chargrid_input/serialize"]
gamepad = ["chargrid_gamepad", "chargrid_input/gamepad", "chargrid_runtime/gamepad"]

[dependencies]
chargrid_graphical_common = { path = "../graphical-common", version = "0.2" }
chargrid_input = { path = "../input", version = "0.2" }
chargrid_gamepad = { path = "../gamepad", version = "0.2", optional = true }
chargrid_runtime = { path = "../runtime", version = "0.1" }
wgpu = "0.12"
wgpu_glyph = "0.16"
winit = "0.26"
zerocopy = "0.6"
log = "0.4"
grid_2d = "0.15"
pollster = "0.2"
async-executor = "1.0"
