[package]
name = "text_field_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chargrid_web = { path = "../../../web" }
text_field_app = { path = "../app" }
wasm-bindgen = "0.2"
