[package]
name = "colour_grid_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
env_logger = "0.9"
chargrid_graphical = { path = "../../../graphical" }
colour_grid_app = { path = "../app" }
