[package]
name = "soundboard_graphical"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[features]
default = ["wgpu"]
wgpu = ["chargrid_graphical/wgpu", "chargrid_graphical/gamepad"]
ggez = ["chargrid_graphical/ggez", "chargrid_graphical/ggez_gamepad"]

[dependencies]
chargrid_graphical = { path = "../../../graphical", default-features = false }
soundboard_app = { path = "../app" }
general_audio_native = { version = "0.3", features = ["vorbis"] }
env_logger = "0.9"
