[package]
name = "chargrid_ggez"
version = "0.1.0"
edition = "2018"

[features]
serialize = ["chargrid_input/serialize", "chargrid_render/serialize"]
gamepad = ["chargrid_input/gamepad"]

[dependencies]
chargrid_render = { path = "../render", version = "0.2" }
chargrid_input = { path = "../input", version = "0.2" }
chargrid_app = { path = "../app", version = "0.2" }
log = "0.4"
ggez = "0.6.0-rc1"
