[package]
name = "chargrid_runtime"
description = "Helpers for implementing chargrid frontends"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gridbugs/chargrid.git"
repository = "https://github.com/gridbugs/chargrid.git"
documentation = "https://docs.rs/chargrid_runtime"
edition = "2021"

[features]
gamepad = ["chargrid_core/gamepad"]

[dependencies]
chargrid_core = { path = "../core", version = "0.1" }
