[package]
name = "chargrid_core"
version = "0.1.0"
edition = "2018"

[features]
serialize = ["chargrid_input/serialize"]
gamepad = ["chargrid_input/gamepad"]

[dependencies]
rgba32 = "0.1"
grid_2d = "0.15"
chargrid_input = { path = "../input", version = "0.2" }
