[package]
name = "tetris_app"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tetris = { path = "../tetris" }
chargrid = { path = "../../../chargrid" }
rand = "0.8"
