[package]
name = "tetris_app"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
tetris = { path = "../tetris" }
chargrid_component = { path = "../../../component" }
chargrid_component_common = { path = "../../../component-common" }
rand = "0.8"
rand_isaac = "0.3"
