[package]
name = "colour_grid_app"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
chargrid_component = { path = "../../../component" }
chargrid_component_common = { path = "../../../component-common" }
