[package]
name = "component_experiment_graphical"
version = "0.1.0"
edition = "2018"

[dependencies]
chargrid_graphical = { path = "../../../graphical" }
chargrid_component = { path = "../../../component", features = ["gamepad"] }
chargrid_component_common = { path = "../../../component-common", features = ["gamepad"] }
