[package]
name = "component_experiment_graphical"
version = "0.1.0"
edition = "2018"

[dependencies]
component_experiment_app = { path = "../app" }
chargrid_graphical = { path = "../../../graphical", features = ["gamepad"] }
