[package]
name = "chargrid_component_common"
version = "0.1.0"
edition = "2018"

[features]
gamepad = ["chargrid_component/gamepad"]


[dependencies]
chargrid_component = { path = "../component", version = "0.1" }
