[package]
name = "component_experiment_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
component_experiment_app = { path = "../app" }
chargrid_wgpu = { path = "../../../wgpu", features = ["gamepad"] }
env_logger = "0.10"
