[package]
name = "chargrid_web"
description = "Web frontend for chargrid."
version = "0.1.1"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/chargrid.git"
repository = "https://github.com/stevebob/chargrid.git"
documentation = "https://docs.rs/chargrid_web"
edition = "2018"

[features]
serialize = ["chargrid_render/serialize", "chargrid_input/serialize"]
gamepad = ["chargrid_gamepad", "chargrid_input/gamepad"]

[dependencies]
chargrid_app = { path = "../app", version = "0.1" }
chargrid_input = { path = "../input", version = "0.1" }
chargrid_render = { path = "../render", version = "0.1" }
chargrid_gamepad = { path = "../gamepad", version = "0.1", optional = true }
wasm-bindgen = "0.2"
js-sys = "0.3"
grid_2d = "0.15"

[dependencies.web-sys]
version = "0.3"
features = [
  'Document',
  'Window',
  'HtmlElement',
  'Element',
  'EventListener',
  'EventTarget',
  'KeyboardEvent',
  'MouseEvent',
  'WheelEvent',
  'Node',
  'HtmlHeadElement',
  'HtmlMediaElement',
  'Performance',
  'CssStyleDeclaration',
  'DomRect',
]
